export default async function ({ w, VIEW }) {

// THIS CONTROLLER GETS CALLED ON EACH VISITOR REQUEST.
// WE CAN UPDATE THE globalThis OBJECT HERE, OR PRE-SET SOME w.v. (WEB VIEW) VARIABLES.

VIEW.TITLE = 'USER SAMPLE';

}
