export default async function ({ w }) {

// THIS CONTROLLER GETS CALLED ON LOADING OF THE server.js AND APPLIES TO ALL SESSIONS.
// WE CAN UPDATE THE globalThis OBJECT HERE, OR PRE-SET SOME w.v. (WEB VIEW) VARIABLES.
// WE CAN ALSO CALL THE MODELS TO DO THINGS LIKE CREATE A DATABASE, ETC.

}
