export default async function ({ w }) {

// THIS CONTROLLER GETS CALLED ON EACH VISITOR REQUEST AND APPLIES ONLY TO THAT SESSION.
// WE CAN UPDATE THE globalThis OBJECT HERE, OR PRE-SET SOME w.v. (WEB VIEW) VARIABLES.

}
